photos/urls.py
from django.urls import path
from . import views

app_name = 'photo'
urlpatterns = [
    path('login/', views.login, name="login"),
    path('accounts/login/', views.login),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),

    path('', views.gallery, name='gallery'),
    path('photo/view/<pk>/', views.view_photo, name='view'),
    path('photo/add/', views.add_photo, name='add'),
    path('photo/update/<pk>/', views.update_photo, name='set_public'),
    path('photo/delete/<pk>/', views.delete_photo, name='del_photo'),
    # # path('del/category/<pk>', views.del_category, name='del_category'),
]

photoshare/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photos.urls')),
]

    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photos/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    """图片分类模型"""
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class Photo(models.Model):
    """照片模型"""
    class Meta:
        verbose_name = '照片'
        verbose_name_plural = verbose_name
    
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='类别')
    public = models.BooleanField(default=True, verbose_name='是否公开')
    image = models.ImageField(null=False, blank=False, verbose_name='缩略图')
    imageHD = models.ImageField(null=True, blank=False, verbose_name='高清图')
    description = models.TextField(verbose_name='简介')

    def __str__(self):
        return self.description

photos/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Enter username...'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Enter password...'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirm password...'})

photos/views.py
from django.conf import settings
from django.contrib.auth.models import AnonymousUser
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login as _login, logout as _logout, get_user_model
from django.contrib.auth.decorators import login_required

from photoshare.utils.image_header import compress_img_by_bytesio
from .models import Category, Photo
from .forms import CustomUserCreationForm
# Create your views here.
from copy import deepcopy

User = get_user_model()


def login(request):
    """登陆视图"""
    page = 'login'

    if request.method == 'POST':
        _next = request.GET.get('next', reverse('photo:gallery'))
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            _login(request, user)
            return redirect(_next)

    return render(request, 'photos/login_register.html', {'page': page})


def logout(request):
    _logout(request)
    return redirect(reverse('photo:login'))


def register(request):
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            _login(request, user)
            return redirect(reverse('photo:gallery'))

    context = {'form': form, 'page': 'register'}
    return render(request, 'photos/login_register.html', context)


def gallery(request):
    """index"""
    user = request.user
    category = request.GET.get('category')

    if isinstance(user, AnonymousUser):
        user = User.objects.get(username=settings.PUBLIC_USER_USERNAME)

    photos = Photo.objects.filter(category__user=user)

    if not request.user.is_authenticated:  # 未登陆只显示公开部分图片
        photos = photos.filter(public=True)

    if category is not None:
        photos = photos.filter(category__name=category)

    categories = Category.objects.filter(user=user)

    context = {'categories': categories, 'photos': photos, 'user': user}
    return render(request, 'photos/gallery.html', context)


@login_required
def add_photo(request):
    """添加图片"""
    if not request.method == 'POST':
        categories = request.user.category_set.all()

        context = {'categories': categories}
        return render(request, 'photos/add.html', context)

    category_name = request.POST.get('category') or request.POST.get('category_new')
    images = request.FILES.getlist('images')
    public = False if request.POST.get('public', '').lower() == 'false' else True
    description = request.POST.get('description', '')

    if not category_name:
        return redirect(reverse('photo:add'))
    if not images:
        return redirect(reverse('photo:add'))

    category, created = Category.objects.get_or_create(name=category_name, user=request.user)

    for imageHD in images:
        field_name = getattr(imageHD, 'field_name', None)

        image_bytesio = compress_img_by_bytesio(imgdata=deepcopy(imageHD.file), image_format=imageHD.file_format, datasize=imageHD.size)
        image = InMemoryUploadedFile(file=image_bytesio,
                                     name=imageHD.name.replace('.' + imageHD.name.split('.')[-1],
                                                               settings.THUMBANIL_SUFFIX + '.' + imageHD.file_format),
                                     content_type=imageHD.content_type, size=None, charset=imageHD.charset,
                                     content_type_extra=imageHD.content_type_extra, field_name=field_name)

        Photo.objects.create(
            category=category,
            description=description,
            image=image,  # 缩略图
            imageHD=imageHD,  # 高清图
            public=public,
        )

    return redirect(reverse('photo:gallery'))


def view_photo(request, pk):
    """查看照片"""
    user = request.user
    photo = Photo.objects.filter(id=pk)

    if user.is_authenticated:
        photo = photo.filter(category__user=user)
    else:
        photo = photo.filter(category__user__username=settings.PUBLIC_USER_USERNAME)

    photo = photo.first()

    return render(request, 'photos/photo.html', {'photo': photo})


def delete_photo(request, pk):
    """delete photo"""
    if not request.user.is_authenticated:
        url = reverse('photo:login') + f'?next={reverse("photo", args=[pk])}'
        return redirect(url)

    Photo.objects.filter(category__user=request.user, id=pk).delete()
    return redirect(reverse('photo:gallery'))


@login_required
def update_photo(request, pk):
    """更新照片信息"""
    # if request.method != 'GET':
    #     return redirect(reverse('photo:view'))
    public = request.GET.get('public')

    photo = Photo.objects.filter(id=pk, category__user=request.user).first()
    # photo = Photo.objects.filter(id=pk, category__user=User.objects.get(username=settings.PUBLIC_USER_USERNAME)).first()

    if photo is None:
        return redirect(reverse('photo:view'))

    if public is not None:
        if public.lower() == 'false':
            photo.public = False
        elif public.lower:
            photo.public = True

    photo.save()
    u = reverse('photo:view', args=[pk])
    return redirect(u)


def del_category(request):
    """delete category"""
    pass

templates/photos/add.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Add Photo</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>

<body class="m-5">
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-4">
                <a href="{% url 'photo:gallery' %}" class="btn btn-dark my-3">Go Back</a>
                <div class="card">


                    <form method='POST' action="" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group m-3">
                            <label>Description</label>
                            <input required name="description" type="text" placeholder="Enter a description"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Select a category</label>
                            <select name="category" class="form-control">
                                <option value="">Select a category...</option>
                                {% for category in categories %}
                                <option value='{{category.name}}'>{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group m-3">
                            <label>Create a new category</label>
                            <input name="category_new" type="text" placeholder="Create a new category"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Upload image</label>
                            <input required name="images" type="file" multiple class="form-control-file">
                        </div>
                        <div class="form-group m-3">

                            <label>Public or not</label>
                            <select name="public" class="form-control">
{#                                    <option value="yes">Public</option>#}
                                    <option value="true">Yes</option>
                                    <option value="false">No</option>
                                </select>
                        </div>

                        <button type='submit' class="btn btn-primary m-3">Submit</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/photos/gallery.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gallery</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <style>
        .image-thumbail {
            height: 200px;
            object-fit: cover;
        }

        .list-group-item a {
            text-decoration: none;
            color: black;
        }
    </style>
</head>

<body class="m-5">

    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {% if request.user.is_authenticated %}
                <p>你好 {{request.user}}</p>
                {% else %}
                    <h6>{{ username }}的画廊</h6>
                {% endif %}
                <div class="card">
                    <div class="card-header">
                        类别
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'photo:gallery' %}">ALL</a>
                        </li>
                        {% for category in categories %}
                        <li class=" list-group-item">
                            <a href="{% url 'photo:gallery' %}?category={{category.name}}">
                                {{category.name}}
                            </a>
                        </li>
                        {% endfor %}

                        {% if request.user.is_authenticated %}
                        <a href="{% url 'photo:logout' %}" class="btn btn-dark btn-block btn-sm m-1">登出</a>
                        {% else %}
                        <a href="{% url 'photo:login' %}" class="btn btn-dark btn-block btn-sm m-1">登陆</a>
                        {% endif %}
                        <a href="{% url 'photo:add' %}" class="btn btn-dark btn-block btn-sm m-1">添加照片</a>
                        <a href="{{ link_about_me }}" class="btn btn-dark btn-block btn-sm m-1">联系作者</a>
                    </ul>
                </div>

            </div>
            <div class="col-md-9">
                <div class="row">

                    {% for photo in photos %}
                    <div class="col-md-4">
                        <div class="card my-2">
                            <img id="image={{ photo.id }}" class="image-thumbail" src="{{photo.image.url}}" alt="Card image cap">

                            <div class="card-body">
                                <small>类别: {{photo.category.name}}</small>
                            </div>
                            <a href="{% url 'photo:view' photo.id %}" class="btn btn-outline-dark btn-sm m-1">View</a>
                        </div>
                    </div>
                    {% empty %}
                    <h3>No photos...</h3>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>

</body>

</html>

templates/photos/login_register.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Login/Regiser</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <style>
        .login--wrapper {
            display: flex;
            align-items: center;
            height: 80vh;
            justify-content: center;
        }

        .form {
            width: 500px;
        }
    </style>
</head>

<body>
    <div class="container">

        <div class="login--wrapper">

            {% if page == 'login' %}
            <form method='post' class="form">
                {% csrf_token %}
                <h1>Login</h1>
                <h4>Login to view photos and share with your friends</h4>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Username</label>
                    <input type="text" class="form-control" name="username" id="exampleInputEmail1"
                        aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" class="form-control" name="password" id="exampleInputPassword1">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
                <p>Don't have an account <a href="{% url 'photo:register' %}">Register</a></p>
            </form>
            {% else %}
            <form method='post'>
                <h1>Register</h1>
                {% csrf_token %}
                {% for field in form %}
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">{{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
                <p>Already have an account <a href="{% url 'photo:login' %}">Login</a></p>

            </form>
            {% endif %}
        </div>

    </div>
</body>

</html>

templates/photos/photo.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Photo</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>

<body class="m-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">

                <a href="{% url 'photo:gallery' %}" class="btn btn-info my-3">回&nbsp退</a>
                {% if request.user.is_authenticated %}
                    {% if photo.public %}
                    <a href="{% url 'photo:set_public' pk=photo.id %}?public=false" class="btn btn-secondary my-3">隐藏</a> <!-- 设置公共或隐藏-->
                    {% else %}
                    <a href="{% url 'photo:set_public'  pk=photo.id %}?public=true" class="btn btn-success my-3">公开</a> <!-- 设置公共或隐藏-->
                    {% endif %}
                    <a href="{% url 'photo:del_photo' pk=photo.id %}" class="btn btn-danger my-3">删&nbsp除</a>
                {% endif %}
                <div style="height: 90vh;">
                    <img style="max-width: 100%; max-height: 100%;" src="{{photo.imageHD.url}}">

                    <p>{{photo.description}}</p>
                </div>

            </div>
        </div>
    </div>

</body>

</html>